apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data

  labels:
    app: mssql-deployment
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
